services:
  # Base services
  cpp:
    container_name: cpp-sandbox
    build:
      context: ./sandboxes/
      dockerfile: cpp.Dockerfile
    read_only: true
    network_mode: none
    cap_drop:
        - ALL
    security-opt:
      - no-new-privileges:true 
    volumes:
      - cpp-sandbox-vol:/home/sandbox

  js:
    container_name: js-sandbox
    build:
      context: ./sandboxes/
      dockerfile: js.Dockerfile
    read_only: true
    network_mode: none
    cap_drop:
        - ALL
    security-opt:
      - no-new-privileges:true 
    volumes:
      - js-sandbox-vol:/home/sandbox

  py:
    container_name: py-sandbox
    build:
      context: ./sandboxes/
      dockerfile: py.Dockerfile
    network_mode: none
    cap_drop:
        - ALL
    security-opt:
      - no-new-privileges:true 
    read_only: true
    volumes:
      - py-sandbox-vol:/home/sandbox

  dockerproxy:
    build: ./dockerproxy/
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/dokcer.sock
    depends_on:
      - cpp
      - js
      - py

  # Backend tests
  test_db:
    image: postgres:alpine
    profiles: [test]
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  test_backend:
    build:
      context: ./backend/
      dockerfile: tests.Dockerfile
    profiles: [test]
    depends_on:
      - test_db
      - dockerproxy

  # Prod Services
  db:
    profile: [prod]
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  backend:
    build:
        context: ./backend/
        dockerfile: Dockerfile
    profile: [prod]
  frontend:
    profile: [prod]
  nginx:
    profile: [prod]

volumes:
  py-sandbox-vol:
    driver: local
    driver_opts:
      type: tmpfs
      o: size=64m,nodev,nosuid,uid=0,gid=0
      device: tmpfs
  js-sandbox-vol:
    driver: local
    driver_opts:
      type: tmpfs
      o: size=64m,nodev,nosuid,uid=0,gid=0
      device: tmpfs
  cpp-sandbox-vol:
    driver: local
    driver_opts:
      type: tmpfs
      o: size=64,nodev,nosuidm,uid=0,gid=0
      device: tmpfs
