"""empty message

Revision ID: 598cbf11c650
Revises: 8b45006849ed
Create Date: 2026-06-08 16:47:33.295360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598cbf11c650'
down_revision: Union[str, Sequence[str], None] = '8b45006849ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_main_db() -> None:
    """Upgrade main_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('room_members_user_id_fkey'), 'room_members', type_='foreignkey')
    op.drop_constraint(op.f('room_members_room_id_fkey'), 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'room_members', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('rooms', 'invite_token',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_constraint(op.f('rooms_owner_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade_main_db() -> None:
    """Downgrade main_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_owner_id_fkey'), 'rooms', 'users', ['owner_id'], ['id'])
    op.alter_column('rooms', 'invite_token',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key(op.f('room_members_room_id_fkey'), 'room_members', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('room_members_user_id_fkey'), 'room_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def upgrade_tests_db() -> None:
    """Upgrade tests_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('room_members_user_id_fkey'), 'room_members', type_='foreignkey')
    op.drop_constraint(op.f('room_members_room_id_fkey'), 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'room_members', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('rooms', 'invite_token',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_constraint(op.f('rooms_owner_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade_tests_db() -> None:
    """Downgrade tests_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_owner_id_fkey'), 'rooms', 'users', ['owner_id'], ['id'])
    op.alter_column('rooms', 'invite_token',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key(op.f('room_members_room_id_fkey'), 'room_members', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('room_members_user_id_fkey'), 'room_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

