"""empty message

Revision ID: 8b45006849ed
Revises: 706acfea56f9
Create Date: 2026-06-06 19:52:59.917535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b45006849ed'
down_revision: Union[str, Sequence[str], None] = '706acfea56f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_main_db() -> None:
    """Upgrade main_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('invite_token', sa.String(length=32), nullable=False))
    op.drop_constraint(op.f('rooms_invite_link_key'), 'rooms', type_='unique')
    op.create_unique_constraint(None, 'rooms', ['invite_token'])
    op.drop_column('rooms', 'invite_link')
    # ### end Alembic commands ###


def downgrade_main_db() -> None:
    """Downgrade main_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('invite_link', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='unique')
    op.create_unique_constraint(op.f('rooms_invite_link_key'), 'rooms', ['invite_link'], postgresql_nulls_not_distinct=False)
    op.drop_column('rooms', 'invite_token')
    # ### end Alembic commands ###


def upgrade_tests_db() -> None:
    """Upgrade tests_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('invite_token', sa.String(length=32), nullable=False))
    op.drop_constraint(op.f('rooms_invite_link_key'), 'rooms', type_='unique')
    op.create_unique_constraint(None, 'rooms', ['invite_token'])
    op.drop_column('rooms', 'invite_link')
    # ### end Alembic commands ###


def downgrade_tests_db() -> None:
    """Downgrade tests_db schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('invite_link', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='unique')
    op.create_unique_constraint(op.f('rooms_invite_link_key'), 'rooms', ['invite_link'], postgresql_nulls_not_distinct=False)
    op.drop_column('rooms', 'invite_token')
    # ### end Alembic commands ###

